version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: chord_redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: chord_api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./app:/app/app  # Hot reload for backend code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    container_name: chord_worker
    env_file: .env
    command: celery -A workers.tasks worker --loglevel=info
    volumes:
      - ./data:/app/data
      - ./app:/app/app # Hot reload for worker code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OMP_NUM_THREADS=1
      - KMP_DUPLICATE_LIB_OK=TRUE
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: chord_ui
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src # Hot reload for React code
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - api
    stdin_open: true
    tty: true